"""
Configuration and constants for the portfolio analysis
"""

# List of Nifty 50 stock symbols (NSE format: SYMBOL.NS)
NIFTY50_SYMBOLS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "KOTAKBANK.NS", "LT.NS", "SBIN.NS",
    "BHARTIARTL.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "HCLTECH.NS", "MARUTI.NS",
    "AXISBANK.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS", "TITAN.NS", "NESTLEIND.NS",
    "POWERGRID.NS", "WIPRO.NS", "TECHM.NS", "DIVISLAB.NS", "GRASIM.NS",
    "CIPLA.NS", "ADANIPORTS.NS", "HDFCLIFE.NS", "BAJAJFINSV.NS", "ONGC.NS",
    "JSWSTEEL.NS", "TATASTEEL.NS", "BPCL.NS", "BRITANNIA.NS", "EICHERMOT.NS",
    "DRREDDY.NS", "COALINDIA.NS", "APOLLOHOSP.NS", "HEROMOTOCO.NS", "M&M.NS",
    "SBILIFE.NS", "INDUSINDBK.NS", "SHREECEM.NS", "NTPC.NS",
    "BAJAJ-AUTO.NS", "ADANIENT.NS", "UPL.NS", "TATAMOTORS.NS", "TATACONSUM.NS"
]

# Technical Analysis Parameters
RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
BB_PERIOD = 20
BB_STD = 2
VOLUME_PERIOD = 20
VOLATILITY_PERIOD = 20
SMA_PERIODS = [20, 50]
EMA_PERIOD = 20
