"""
Configuration and constants for the portfolio analysis
"""
import os

# List of Nifty 50 stock symbols (NSE format: SYMBOL.NS)
NIFTY50_SYMBOLS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "KOTAKBANK.NS", "LT.NS", "SBIN.NS",
    "BHARTIARTL.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "HCLTECH.NS", "MARUTI.NS",
    "AXISBANK.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS", "TITAN.NS", "NESTLEIND.NS",
    "POWERGRID.NS", "WIPRO.NS", "TECHM.NS", "DIVISLAB.NS", "GRASIM.NS",
    "CIPLA.NS", "ADANIPORTS.NS", "HDFCLIFE.NS", "BAJAJFINSV.NS", "ONGC.NS",
    "JSWSTEEL.NS", "TATASTEEL.NS", "BPCL.NS", "BRITANNIA.NS", "EICHERMOT.NS",
    "DRREDDY.NS", "COALINDIA.NS", "APOLLOHOSP.NS", "HEROMOTOCO.NS", "M&M.NS",
    "SBILIFE.NS", "INDUSINDBK.NS", "SHREECEM.NS", "NTPC.NS",
    "BAJAJ-AUTO.NS", "ADANIENT.NS", "UPL.NS", "TATAMOTORS.NS", "TATACONSUM.NS"
]

NIFTY500_SYMBOLS = [
    "360ONE.NS", "3MINDIA.NS", "ABB.NS", "ACC.NS", "ACMESOLAR.NS",
    "AIAENG.NS", "APLAPOLLO.NS", "AUBANK.NS", "AWL.NS", "AADHARHFC.NS",
    "AARTIIND.NS", "AAVAS.NS", "ABBOTINDIA.NS", "ACE.NS", "ADANIENSOL.NS",
    "ADANIENT.NS", "ADANIGREEN.NS", "ADANIPORTS.NS", "ADANIPOWER.NS", "ATGL.NS",
    "ABCAPITAL.NS", "ABFRL.NS", "ABREL.NS", "ABSLAMC.NS", "AEGISLOG.NS",
    "AFCONS.NS", "AFFLE.NS", "AJANTPHARM.NS", "AKUMS.NS", "APLLTD.NS",
    "ALIVUS.NS", "ALKEM.NS", "ALKYLAMINE.NS", "ALOKINDS.NS", "ARE&M.NS",
    "AMBER.NS", "AMBUJACEM.NS", "ANANDRATHI.NS", "ANANTRAJ.NS", "ANGELONE.NS",
    "APARINDS.NS", "APOLLOHOSP.NS", "APOLLOTYRE.NS", "APTUS.NS", "ASAHIINDIA.NS",
    "ASHOKLEY.NS", "ASIANPAINT.NS", "ASTERDM.NS", "ASTRAZEN.NS", "ASTRAL.NS",
    "ATUL.NS", "AUROPHARMA.NS", "AIIL.NS", "DMART.NS", "AXISBANK.NS",
    "BASF.NS", "BEML.NS", "BLS.NS", "BSE.NS", "BAJAJ-AUTO.NS",
    "BAJFINANCE.NS", "BAJAJFINSV.NS", "BAJAJHLDNG.NS", "BAJAJHFL.NS", "BALKRISIND.NS",
    "BALRAMCHIN.NS", "BANDHANBNK.NS", "BANKBARODA.NS", "BANKINDIA.NS", "MAHABANK.NS",
    "BATAINDIA.NS", "BAYERCROP.NS", "BERGEPAINT.NS", "BDL.NS", "BEL.NS",
    "BHARATFORG.NS", "BHEL.NS", "BPCL.NS", "BHARTIARTL.NS", "BHARTIHEXA.NS",
    "BIKAJI.NS", "BIOCON.NS", "BSOFT.NS", "BLUEDART.NS", "BLUESTARCO.NS",
    "BBTC.NS", "BOSCHLTD.NS", "FIRSTCRY.NS", "BRIGADE.NS", "BRITANNIA.NS",
    "MAPMYINDIA.NS", "CCL.NS", "CESC.NS", "CGPOWER.NS", "CRISIL.NS",
    "CAMPUS.NS", "CANFINHOME.NS", "CANBK.NS", "CAPLIPOINT.NS", "CGCL.NS",
    "CARBORUNIV.NS", "CASTROLIND.NS", "CEATLTD.NS", "CENTRALBK.NS", "CDSL.NS",
    "CENTURYPLY.NS", "CERA.NS", "CHALET.NS", "CHAMBLFERT.NS", "CHENNPETRO.NS",
    "CHOLAHLDNG.NS", "CHOLAFIN.NS", "CIPLA.NS", "CUB.NS", "CLEAN.NS",
    "COALINDIA.NS", "COCHINSHIP.NS", "COFORGE.NS", "COHANCE.NS", "COLPAL.NS",
    "CAMS.NS", "CONCORDBIO.NS", "CONCOR.NS", "COROMANDEL.NS", "CRAFTSMAN.NS",
    "CREDITACC.NS", "CROMPTON.NS", "CUMMINSIND.NS", "CYIENT.NS", "DCMSHRIRAM.NS",
    "DLF.NS", "DOMS.NS", "DABUR.NS", "DALBHARAT.NS", "DATAPATTNS.NS",
    "DEEPAKFERT.NS", "DEEPAKNTR.NS", "DELHIVERY.NS", "DEVYANI.NS", "DIVISLAB.NS",
    "DIXON.NS", "LALPATHLAB.NS", "DRREDDY.NS", "EIDPARRY.NS", "EIHOTEL.NS",
    "EICHERMOT.NS", "ELECON.NS", "ELGIEQUIP.NS", "EMAMILTD.NS", "EMCURE.NS",
    "ENDURANCE.NS", "ENGINERSIN.NS", "ERIS.NS", "ESCORTS.NS", "ETERNAL.NS",
    "EXIDEIND.NS", "NYKAA.NS", "FEDERALBNK.NS", "FACT.NS", "FINCABLES.NS",
    "FINPIPE.NS", "FSL.NS", "FIVESTAR.NS", "FORTIS.NS", "GAIL.NS",
    "GVT&D.NS", "GMRAIRPORT.NS", "GRSE.NS", "GICRE.NS", "GILLETTE.NS",
    "GLAND.NS", "GLAXO.NS", "GLENMARK.NS", "MEDANTA.NS", "GODIGIT.NS",
    "GPIL.NS", "GODFRYPHLP.NS", "GODREJAGRO.NS", "GODREJCP.NS", "GODREJIND.NS",
    "GODREJPROP.NS", "GRANULES.NS", "GRAPHITE.NS", "GRASIM.NS", "GRAVITA.NS",
    "GESHIP.NS", "FLUOROCHEM.NS", "GUJGASLTD.NS", "GMDCLTD.NS", "GNFC.NS",
    "GPPL.NS", "GSPL.NS", "HEG.NS", "HBLENGINE.NS", "HCLTECH.NS",
    "HDFCAMC.NS", "HDFCBANK.NS", "HDFCLIFE.NS", "HFCL.NS", "HAPPSTMNDS.NS",
    "HAVELLS.NS", "HEROMOTOCO.NS", "HSCL.NS", "HINDALCO.NS", "HAL.NS",
    "HINDCOPPER.NS", "HINDPETRO.NS", "HINDUNILVR.NS", "HINDZINC.NS", "POWERINDIA.NS",
    "HOMEFIRST.NS", "HONASA.NS", "HONAUT.NS", "HUDCO.NS", "HYUNDAI.NS",
    "ICICIBANK.NS", "ICICIGI.NS", "ICICIPRULI.NS", "IDBI.NS", "IDFCFIRSTB.NS",
    "IFCI.NS", "IIFL.NS", "INOXINDIA.NS", "IRB.NS", "IRCON.NS",
    "ITC.NS", "ITI.NS", "INDGN.NS", "INDIACEM.NS", "INDIAMART.NS",
    "INDIANB.NS", "IEX.NS", "INDHOTEL.NS", "IOC.NS", "IOB.NS",
    "IRCTC.NS", "IRFC.NS", "IREDA.NS", "IGL.NS", "INDUSTOWER.NS",
    "INDUSINDBK.NS", "NAUKRI.NS", "INFY.NS", "INOXWIND.NS", "INTELLECT.NS",
    "INDIGO.NS", "IGIL.NS", "IKS.NS", "IPCALAB.NS", "JBCHEPHARM.NS",
    "JKCEMENT.NS", "JBMA.NS", "JKTYRE.NS", "JMFINANCIL.NS", "JSWENERGY.NS",
    "JSWHL.NS", "JSWINFRA.NS", "JSWSTEEL.NS", "JPPOWER.NS", "J&KBANK.NS",
    "JINDALSAW.NS", "JSL.NS", "JINDALSTEL.NS", "JIOFIN.NS", "JUBLFOOD.NS",
    "JUBLINGREA.NS", "JUBLPHARMA.NS", "JWL.NS", "JUSTDIAL.NS", "JYOTHYLAB.NS",
    "JYOTICNC.NS", "KPRMILL.NS", "KEI.NS", "KNRCON.NS", "KPITTECH.NS",
    "KAJARIACER.NS", "KPIL.NS", "KALYANKJIL.NS", "KANSAINER.NS", "KARURVYSYA.NS",
    "KAYNES.NS", "KEC.NS", "KFINTECH.NS", "KIRLOSBROS.NS", "KIRLOSENG.NS",
    "KOTAKBANK.NS", "KIMS.NS", "LTF.NS", "LTTS.NS", "LICHSGFIN.NS",
    "LTFOODS.NS", "LTIM.NS", "LT.NS", "LATENTVIEW.NS", "LAURUSLABS.NS",
    "LEMONTREE.NS", "LICI.NS", "LINDEINDIA.NS", "LLOYDSME.NS", "LODHA.NS",
    "LUPIN.NS", "MMTC.NS", "MRF.NS", "MGL.NS", "MAHSEAMLES.NS",
    "M&MFIN.NS", "M&M.NS", "MANAPPURAM.NS", "MRPL.NS", "MANKIND.NS",
    "MARICO.NS", "MARUTI.NS", "MASTEK.NS", "MFSL.NS", "MAXHEALTH.NS",
    "MAZDOCK.NS", "METROPOLIS.NS", "MINDACORP.NS", "MSUMI.NS", "MOTILALOFS.NS",
    "MPHASIS.NS", "MCX.NS", "MUTHOOTFIN.NS", "NATCOPHARM.NS", "NBCC.NS",
    "NCC.NS", "NHPC.NS", "NLCINDIA.NS", "NMDC.NS", "NSLNISP.NS",
    "NTPCGREEN.NS", "NTPC.NS", "NH.NS", "NATIONALUM.NS", "NAVA.NS",
    "NAVINFLUOR.NS", "NESTLEIND.NS", "NETWEB.NS", "NETWORK18.NS", "NEULANDLAB.NS",
    "NEWGEN.NS", "NAM-INDIA.NS", "NIVABUPA.NS", "NUVAMA.NS", "OBEROIRLTY.NS",
    "ONGC.NS", "OIL.NS", "OLAELEC.NS", "OLECTRA.NS", "PAYTM.NS",
    "OFSS.NS", "POLICYBZR.NS", "PCBL.NS", "PGEL.NS", "PIIND.NS",
    "PNBHOUSING.NS", "PNCINFRA.NS", "PTCIL.NS", "PVRINOX.NS", "PAGEIND.NS",
    "PATANJALI.NS", "PERSISTENT.NS", "PETRONET.NS", "PFIZER.NS", "PHOENIXLTD.NS",
    "PIDILITIND.NS", "PEL.NS", "PPLPHARMA.NS", "POLYMED.NS", "POLYCAB.NS",
    "POONAWALLA.NS", "PFC.NS", "POWERGRID.NS", "PRAJIND.NS", "PREMIERENE.NS",
    "PRESTIGE.NS", "PNB.NS", "RRKABEL.NS", "RBLBANK.NS", "RECLTD.NS",
    "RHIM.NS", "RITES.NS", "RADICO.NS", "RVNL.NS", "RAILTEL.NS",
    "RAINBOW.NS", "RKFORGE.NS", "RCF.NS", "RTNINDIA.NS", "RAYMONDLSL.NS",
    "RAYMOND.NS", "REDINGTON.NS", "RELIANCE.NS", "RPOWER.NS", "ROUTE.NS",
    "SBFC.NS", "SBICARD.NS", "SBILIFE.NS", "SJVN.NS", "SKFINDIA.NS",
    "SRF.NS", "SAGILITY.NS", "SAILIFE.NS", "SAMMAANCAP.NS", "MOTHERSON.NS",
    "SAPPHIRE.NS", "SARDAEN.NS", "SAREGAMA.NS", "SCHAEFFLER.NS", "SCHNEIDER.NS",
    "SCI.NS", "SHREECEM.NS", "RENUKA.NS", "SHRIRAMFIN.NS", "SHYAMMETL.NS",
    "SIEMENS.NS", "SIGNATURE.NS", "SOBHA.NS", "SOLARINDS.NS", "SONACOMS.NS",
    "SONATSOFTW.NS", "STARHEALTH.NS", "SBIN.NS", "SAIL.NS", "SWSOLAR.NS",
    "SUMICHEM.NS", "SUNPHARMA.NS", "SUNTV.NS", "SUNDARMFIN.NS", "SUNDRMFAST.NS",
    "SUPREMEIND.NS", "SUZLON.NS", "SWANENERGY.NS", "SWIGGY.NS", "SYNGENE.NS",
    "SYRMA.NS", "TBOTEK.NS", "TVSMOTOR.NS", "TANLA.NS", "TATACHEM.NS",
    "TATACOMM.NS", "TCS.NS", "TATACONSUM.NS", "TATAELXSI.NS", "TATAINVEST.NS",
    "TATAMOTORS.NS", "TATAPOWER.NS", "TATASTEEL.NS", "TATATECH.NS", "TTML.NS",
    "TECHM.NS", "TECHNOE.NS", "TEJASNET.NS", "NIACL.NS", "RAMCOCEM.NS",
    "THERMAX.NS", "TIMKEN.NS", "TITAGARH.NS", "TITAN.NS", "TORNTPHARM.NS",
    "TORNTPOWER.NS", "TARIL.NS", "TRENT.NS", "TRIDENT.NS", "TRIVENI.NS",
    "TRITURBINE.NS", "TIINDIA.NS", "UCOBANK.NS", "UNOMINDA.NS", "UPL.NS",
    "UTIAMC.NS", "ULTRACEMCO.NS", "UNIONBANK.NS", "UBL.NS", "UNITDSPR.NS",
    "USHAMART.NS", "VGUARD.NS", "DBREALTY.NS", "VTL.NS", "VBL.NS",
    "MANYAVAR.NS", "VEDL.NS", "VIJAYA.NS", "VMM.NS", "IDEA.NS",
    "VOLTAS.NS", "WAAREEENER.NS", "WELCORP.NS", "WELSPUNLIV.NS", "WESTLIFE.NS",
    "WHIRLPOOL.NS", "WIPRO.NS", "WOCKPHARMA.NS", "YESBANK.NS", "ZFCVINDIA.NS",
    "ZEEL.NS", "ZENTEC.NS", "ZENSARTECH.NS", "ZYDUSLIFE.NS", "ECLERX.NS"
]

# === Your portfolio (NSE symbols) ===
POSITIONS = [
    "AADHARHFC.NS",
    "BANDHANBNK.NS",
    "CAMS.NS",
    "CDSL.NS",
    "ELECTCAST.NS",
    "FIEMIND.NS",
    "HDFCBANK.NS",
    "INFY.NS",
    "JPPOWER.NS",
    "MOTISONS.NS",
    "OLAELEC.NS",
    "ONGC.NS",
    "POLYMED.NS",
    "RAMCOCEM.NS",
    "RELIANCE.NS",
    "TATAMOTORS.NS",
    "TCS.NS",
    "THEMISMED.NS",
    "UNIPARTS.NS",
    "VPRPL.NS",
    "YOGISUNG.BO",
    "VPRpL.NS",
    "WALCHANNAG.NS",
    "OLAELEC.NS",
    "LCID",
    "WABAG.NS",
    "KPIGREEN.NS",
    "SBCL.NS",
    "DCXINDIA.NS",
    "AVALON.NS",
    "CYIENTDLM.NS",
    "IDEAFORGE.NS",
    "FUSION.NS",
]

PORTFOLIO_WATCHLIST = POSITIONS
# Technical Analysis Parameters
RSI_PERIOD = 14
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL = 9
BB_PERIOD = 20
BB_STD = 2
VOLUME_PERIOD = 20
VOLATILITY_PERIOD = 20
SMA_PERIODS = [20, 50]
EMA_PERIOD = 20

# -----------------------------
# Email & Notification Settings
# -----------------------------

# Email sending is disabled by default; enable by setting MAIL_ENABLED=1
MAIL_ENABLED = '1'
MAIL_SERVER = os.getenv('MAIL_SERVER', 'smtp.gmail.com')
MAIL_PORT = int(os.getenv('MAIL_PORT', '587'))
MAIL_USE_TLS = (os.getenv('MAIL_USE_TLS', '1') == '1')
MAIL_USERNAME = os.getenv('MAIL_USERNAME', '')
MAIL_PASSWORD = os.getenv('MAIL_PASSWORD', '')
MAIL_FROM = os.getenv('MAIL_FROM', MAIL_USERNAME or 'alerts@example.com')

# Comma-separated list of recipients
MAIL_TO = [e.strip() for e in os.getenv('MAIL_TO', '').split(',') if e.strip()] or []

# Reversal email defaults (overridable via CLI flags/env)
REVERSALS_EMAIL_UNIVERSE = os.getenv('REVERSALS_EMAIL_UNIVERSE', 'n500')  # n50|n500|watch
# Typical reversal scores fall roughly within 0–30. Use a modest default.
REVERSALS_EMAIL_MIN_SCORE = float(os.getenv('REVERSALS_EMAIL_MIN_SCORE', '10'))
REVERSALS_EMAIL_TOP_N = int(os.getenv('REVERSALS_EMAIL_TOP_N', '10'))

# Subject prefix for emails
MAIL_SUBJECT_PREFIX = os.getenv('MAIL_SUBJECT_PREFIX', '[Plutus]')

# -----------------------------
# Email Command Trigger (IMAP Poller)
# -----------------------------

# Enable inbound email commands (polls IMAP for trigger messages)
MAIL_COMMANDS_ENABLED = (os.getenv('MAIL_COMMANDS_ENABLED', '0') == '1')
IMAP_SERVER = os.getenv('IMAP_SERVER', 'imap.gmail.com')
IMAP_PORT = int(os.getenv('IMAP_PORT', '993'))
IMAP_USE_SSL = (os.getenv('IMAP_USE_SSL', '1') == '1')

# Only process messages whose Subject contains this keyword (case-insensitive)
MAIL_COMMAND_TRIGGER_SUBJECT = os.getenv('MAIL_COMMAND_TRIGGER_SUBJECT', 'plutus')

# Allowed sender emails (comma-separated). Empty = allow any sender.
MAIL_COMMAND_ALLOWED_SENDERS = [e.strip().lower() for e in os.getenv('MAIL_COMMAND_ALLOWED_SENDERS', '').split(',') if e.strip()]

# Reply behavior: when true, respond to the sender; otherwise use MAIL_TO list
MAIL_COMMAND_REPLY_TO_SENDER = (os.getenv('MAIL_COMMAND_REPLY_TO_SENDER', '1') == '1')

# Poll interval seconds
MAIL_COMMAND_POLL_INTERVAL = int(os.getenv('MAIL_COMMAND_POLL_INTERVAL', '60'))
