version: '3.8'

services:
  web:
    build: .
    container_name: portfolio-web
    environment:
      FLASK_APP: webapp.py
      FLASK_ENV: development
      FLASK_DEBUG: "1"
    command: python -m flask run --host=0.0.0.0 --port=8080 --reload
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped

